apiVersion: apps/v1
kind: Deployment
metadata:
  name: landing-page-deployment
  namespace: production
  labels:
    app: landing-page-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: landing-page-deployment
  template:
    metadata:
      labels:
        app: landing-page-deployment
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: landing-page-deployment
        image: fiardika/landing-page-jenkins:latest
        imagePullPolicy: "Always"
        ports:
        - containerPort: 80

---

kind: Service
apiVersion: v1
metadata:
  name: landing-page-service
  namespace: production
spec:
  selector:
    app: landing-page-deployment
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
